### ISSUE TITLE
[sflphone-kde] Nice work!

### ISSUE THREAD

**Issue by psi-4ward** [Lekensteyn/aur#2]
Hey thanks for nice work!

`LC_ALL=C` was added to have "understandable" error messages for users with foreign system languages like me (german).

can you add a `mkaurball`, ill update the AUR with it

**Comment by Lekensteyn** [comment]
The src tarball can be found here: https://lekensteyn.nl/junk/sflphone-kde-1.4.1-2.src.tar.gz (I'll remove it when you got it).

To get "understandable messages", you can also set it outside makepkg: `LANG=en_US.UTF-8 makepkg`

As for the `-j`, you can add this to your `~/.makepkg.conf` to get an appropriate -j option depending on the number of processing units:
```sh
MAKEFLAGS="-j$(nproc)"
```

**Comment by psi-4ward** [comment]
`==> ERROR: install file (('sflphone-kde.install')) does not exist.`
fixed it with
`install="${pkgname}.install"` (no parenthesis)

Updated AUR

**Comment by Lekensteyn** [comment]
pacman 4.2 did not give me any errors. Thanks for reporting, fixed it!
