### ISSUE TITLE
How do I apply this patch to usbmuxd?

### ISSUE THREAD

**Issue by khyfry** [Lekensteyn/aur#3]
I'm so confused. please help

**Comment by Lekensteyn** [comment]
OpenSUSE user I guess?

Just install usbmuxd 1.0.9 or 1.1.0, these versions have the patch already incorporated.

**Comment by khyfry** [comment]
Yeah, using OpenSUSE

Okay, thank you. I'm still having issues then. in DFU mode it halts at about 66% of uploading iBEC.

**Comment by Lekensteyn** [comment]
That is unfortunate, but it better handled at the libimobiledevice issue trackers as it gets better exposure.
